# Archetype-aware AI artifact installation.
#
# Installs generated instruction files, skills, and role agent profiles from
# the committed ai-artifacts/ tree (or local checkout in development mode).
#
# The artifact tree is generated by `generate-ai-artifacts` from
# conventions/archetypes.yaml and committed for PR review.  See the issue
# #218 architecture diagram for the full flow.
#
# Development mode (REQ-14 through REQ-17):
#   keystone.development = true  → symlink to local repo ai-artifacts/
#   keystone.development = false → Nix store copy from committed tree
{
  config,
  lib,
  pkgs,
  ...
}:
with lib;
let
  cfg = config.keystone.terminal.aiArtifacts;
  terminalCfg = config.keystone.terminal;
  conventionsCfg = config.keystone.terminal.conventions;
  isDev = config.keystone.development;
  repos = config.keystone.repos;
  homeDir = config.home.homeDirectory;

  # Look up the keystone repo's local checkout path (same pattern as deepwork.nix)
  keystoneEntry = findFirst (name: (repos.${name}.flakeInput or null) == "keystone") null (
    attrNames repos
  );
  devPath =
    if isDev && keystoneEntry != null then "${homeDir}/.keystone/repos/${keystoneEntry}" else null;

  # Resolve the artifact tree root: local checkout or Nix store.
  artifactTreeRoot =
    if devPath != null then
      "${devPath}/ai-artifacts"
    else
      "${pkgs.keystone.keystone-conventions}/../ai-artifacts";

  # Per-archetype artifact directory
  archetypeDir = "${artifactTreeRoot}/archetypes/${cfg.archetype}";

  # Tool directories that map to home directory install paths
  toolInstallPaths = {
    claude = {
      instructionDest = ".claude/CLAUDE.md";
      instructionSrc = "claude/CLAUDE.md";
      skillPrefix = ".claude/skills";
    };
    gemini = {
      instructionDest = ".gemini/GEMINI.md";
      instructionSrc = "gemini/GEMINI.md";
      skillPrefix = ".gemini/skills";
    };
    codex = {
      instructionDest = ".codex/AGENTS.md";
      instructionSrc = "codex/AGENTS.md";
      skillPrefix = ".codex/skills";
    };
    opencode = {
      instructionDest = ".config/opencode/AGENTS.md";
      instructionSrc = "opencode/AGENTS.md";
      skillPrefix = ".config/opencode/skills";
    };
  };

  # Filter to only enabled tools
  enabledTools = filterAttrs (name: _: cfg.tools.${name}.enable) toolInstallPaths;
in
{
  options.keystone.terminal.aiArtifacts = {
    enable = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Install archetype-aware AI artifacts (instruction files, skills,
        and role agent profiles) from the committed artifact tree.
        See conventions/archetypes.yaml for available archetypes.
      '';
    };

    archetype = mkOption {
      type = types.str;
      default = conventionsCfg.archetype;
      description = ''
        The archetype whose artifacts to install.  Defaults to the same
        archetype used by conventions.nix so users don't set it twice
        (REQ-28).
      '';
    };

    tools = {
      claude = {
        enable = mkOption {
          type = types.bool;
          default = true;
          description = "Install Claude Code AI artifacts.";
        };
      };
      gemini = {
        enable = mkOption {
          type = types.bool;
          default = true;
          description = "Install Gemini CLI AI artifacts.";
        };
      };
      codex = {
        enable = mkOption {
          type = types.bool;
          default = true;
          description = "Install Codex AI artifacts.";
        };
      };
      opencode = {
        enable = mkOption {
          type = types.bool;
          default = true;
          description = "Install OpenCode AI artifacts.";
        };
      };
    };
  };

  config = mkIf (terminalCfg.enable && terminalCfg.ai.enable && cfg.enable) {
    # Expose the artifact tree root for other modules to reference
    home.sessionVariables = {
      KEYSTONE_AI_ARTIFACTS = archetypeDir;
    };
  };
}
