# Keystone NixOS Configuration - Apple Silicon
# Generated by install-apple-silicon
{
  config,
  pkgs,
  lib,
  ...
}: {
  imports = [./hardware-configuration.nix];

  # ============================================================================
  # SYSTEM IDENTITY
  # ============================================================================

  networking.hostName = "keystone-mac";
  system.stateVersion = "25.05";

  # ============================================================================
  # NIXPKGS CONFIGURATION
  # ============================================================================

  # Allow unfree packages (for Claude Code, etc.)
  nixpkgs.config.allowUnfree = true;

  # ============================================================================
  # KEYSTONE DESKTOP (SYSTEM LEVEL)
  # ============================================================================

  # Enable greetd, Hyprland, PipeWire, Bluetooth at system level
  keystone.desktop = {
    enable = true;
    user = "admin"; # User for auto-login to Hyprland session
  };

  # ============================================================================
  # APPLE SILICON BOOT CONFIGURATION
  # ============================================================================

  # CRITICAL: U-Boot cannot write EFI variables - this prevents bricking!
  boot.loader.efi.canTouchEfiVariables = lib.mkForce false;
  boot.loader.systemd-boot.enable = true;
  boot.loader.systemd-boot.consoleMode = "0";

  # ============================================================================
  # NETWORKING
  # ============================================================================

  networking.networkmanager.enable = true;
  networking.networkmanager.wifi.backend = "iwd";
  networking.wireless.iwd.enable = true;

  # ============================================================================
  # USERS
  # ============================================================================

  users.users.admin = {
    isNormalUser = true;
    description = "System Administrator";
    extraGroups = ["wheel" "networkmanager" "video" "audio"];
    initialPassword = "changeme"; # TODO: Change after first login!
  };

  # ============================================================================
  # HOME-MANAGER - USER DESKTOP CONFIGURATION
  # ============================================================================

  # Required for XDG portal integration with home-manager
  environment.pathsToLink = ["/share/applications" "/share/xdg-desktop-portal"];

  home-manager.users.admin = {pkgs, ...}: {
    home.stateVersion = "25.05";

    # Enable Keystone desktop (Hyprland)
    keystone.desktop = {
      enable = true;
      hyprland = {
        enable = true;
        modifierKey = "SUPER"; # Command key as modifier
        capslockAsControl = true;
        scale = 2; # HiDPI for Retina display
      };
    };

    # Enable Keystone terminal tools
    keystone.terminal = {
      enable = true;
      git = {
        userName = "Admin";
        userEmail = "admin@keystone-mac";
      };
    };
  };

  # ============================================================================
  # SERVICES
  # ============================================================================

  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "prohibit-password";
      PasswordAuthentication = true; # TODO: Set to false after adding SSH keys
    };
  };

  # ============================================================================
  # NIX SETTINGS
  # ============================================================================

  nix.settings = {
    experimental-features = ["nix-command" "flakes"];
    trusted-users = ["root" "@wheel"];
  };

  # ============================================================================
  # PACKAGES
  # ============================================================================

  environment.systemPackages = with pkgs; [
    vim
    git
    curl
    wget
    htop
    tree
  ];

  # Timezone
  time.timeZone = "UTC"; # TODO: Change to your timezone
}
