# Service account CLI configuration test
#
# Verifies that agent CLI tools receive correct configuration and credentials
# after the Forgejo provisioning service completes:
#
#   1. Pre-seeded tea config and fj keys.json exist (simulating home-manager output).
#   2. The provision-agent-git service writes the persistent API token into
#      the tea config and fj keys.json (as generated by provision-agent-git.sh).
#   3. The tea config contains a non-empty token field after provisioning.
#   4. The fj keys.json contains the expected host entry with a token.
#   5. Idempotency: re-running the provision service does NOT change the token.
#
# This test exercises the token-writing logic in provision-agent-git.sh
# (the real script from the keystone source tree) against a live Forgejo
# instance. Forgejo is configured directly to avoid unrelated agenix
# assertions from the keystone mail-client module.
#
# ISSUE-REQ-12, ISSUE-REQ-14
#
# Build:       nix build .#checks.x86_64-linux.test-service-account-cli-config
# Interactive: nix build .#checks.x86_64-linux.test-service-account-cli-config.driverInteractive
{
  pkgs,
  lib,
  self,
  home-manager,
}:
pkgs.testers.nixosTest {
  name = "service-account-cli-config";

  nodes.machine =
    { config, pkgs, ... }:
    {
      services.forgejo = {
        enable = true;
        package = pkgs.forgejo;
        stateDir = "/var/lib/forgejo";
        settings = {
          server = {
            DOMAIN = "machine";
            ROOT_URL = "http://machine:3000/";
            HTTP_PORT = 3000;
            SSH_PORT = 2222;
            START_SSH_SERVER = true;
          };
          database.DB_TYPE = "sqlite3";
          repository.ROOT = "/var/lib/forgejo/repositories";
          service = {
            DISABLE_REGISTRATION = false;
            REQUIRE_SIGNIN_VIEW = false;
          };
          actions.ENABLED = false;
          security.INSTALL_LOCK = true;
        };
      };

      # Agent user with home directory
      users.users.agent-test = {
        isNormalUser = true;
        uid = 4001;
        home = "/home/agent-test";
        createHome = true;
        initialPassword = "unused";
        shell = pkgs.bash;
      };
      users.groups.agents = {
        members = [ "agent-test" ];
      };

      # Pre-create CLI config files that home-manager would normally write.
      # The provisioning service checks for these files before writing tokens —
      # if they are absent the token is silently skipped (correct behaviour).
      system.activationScripts.pre-seed-cli-configs = {
        text = ''
          TEA_DIR="/home/agent-test/.config/tea"
          FJ_DIR="/home/agent-test/.local/share/forgejo-cli"
          mkdir -p "$TEA_DIR" "$FJ_DIR"

          # tea config: empty token (provisioning will fill it in)
          if [ ! -f "$TEA_DIR/config.yml" ]; then
            printf '%s\n' \
              '{"logins":[{"name":"forgejo","url":"http://machine:3000","token":"","default":true,"ssh_host":"machine","ssh_key":"~/.ssh/id_ed25519","ssh_agent":true,"version_check":false,"user":"test"}],"preferences":{"editor":false,"flag_defaults":{"remote":""}}}' \
              > "$TEA_DIR/config.yml"
          fi

          # fj keys.json: alias only, no token yet
          if [ ! -f "$FJ_DIR/keys.json" ]; then
            printf '%s\n' \
              '{"hosts":{},"aliases":{"machine:2222":"machine"},"default_ssh":[]}' \
              > "$FJ_DIR/keys.json"
          fi

          chown -R agent-test:agents "$TEA_DIR" "$FJ_DIR"
          chmod 0600 "$TEA_DIR/config.yml" "$FJ_DIR/keys.json"
        '';
        deps = [ "users" ];
      };

      environment.systemPackages = [
        pkgs.forgejo
        pkgs.git
        pkgs.jq
      ];

      systemd.services.provision-agent-git-test = {
        description = "Provision Forgejo CLI config and API token for agent-test";
        after = [
          "forgejo.service"
          "pre-seed-cli-configs.service"
        ];
        requires = [ "forgejo.service" ];
        wantedBy = [ "multi-user.target" ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
        };
        path = [
          pkgs.forgejo
          pkgs.curl
          pkgs.jq
          pkgs.coreutils
          pkgs.sudo
          pkgs.yq-go
        ];
        environment = {
          FORGEJO_USER = "forgejo";
          STATE_DIR = "/var/lib/forgejo";
          API_URL = "http://127.0.0.1:3000/api/v1";
          USERNAME = "test";
          EMAIL = "agent-test@test.local";
          REPO_NAME = "notes";
          AGENT_NAME = "test";
          DOMAIN = "machine";
          AGENT_PUBKEY = "";
          ADMIN_USERS_JSON = "[]";
        };
        script = builtins.readFile "${self}/modules/os/git-server/scripts/provision-agent-git.sh";
      };

      networking.useDHCP = false;
      networking.interfaces.eth0.useDHCP = true;

      virtualisation = {
        memorySize = 3072;
        cores = 2;
      };
    };

  testScript = ''
    import json

    print("=== service-account-cli-config: starting test ===")
    machine.wait_for_unit("multi-user.target")
    print("System booted")

    machine.wait_for_unit("forgejo.service", timeout=120)
    machine.wait_for_open_port(3000, timeout=120)
    print("Forgejo ready")

    machine.wait_for_unit("provision-agent-git-test.service", timeout=300)
    print("Provisioning service completed")

    # --- Verify tea config received an API token ---
    tea_raw = machine.succeed(
      "cat /home/agent-test/.config/tea/config.yml"
    )
    print(f"tea config:\n{tea_raw}")
    tea_data = json.loads(tea_raw)
    logins = tea_data.get("logins", [])
    assert len(logins) > 0, "Expected at least one login entry in tea config"
    token = logins[0].get("token", "")
    assert token != "", f"Expected non-empty API token in tea config, got: {token!r}"
    print(f"PASS: tea config has non-empty API token ({len(token)} chars)")

    # --- Verify fj keys.json received host+token entry ---
    fj_raw = machine.succeed(
      "cat /home/agent-test/.local/share/forgejo-cli/keys.json"
    )
    print(f"fj keys.json:\n{fj_raw}")
    fj_data = json.loads(fj_raw)
    hosts = fj_data.get("hosts", {})
    assert "machine" in hosts, (
      f"Expected 'machine' key in fj hosts, got: {list(hosts.keys())}"
    )
    host_token = hosts["machine"].get("token", "")
    assert host_token != "", "Expected non-empty token in fj hosts['machine']"
    print(f"PASS: fj keys.json has host entry for 'machine' with API token")

    # --- Idempotency: re-run must not change the token (ISSUE-REQ-14) ---
    machine.succeed("systemctl restart provision-agent-git-test.service")
    machine.wait_for_unit("provision-agent-git-test.service", timeout=120)
    tea_raw2 = machine.succeed("cat /home/agent-test/.config/tea/config.yml")
    token2 = json.loads(tea_raw2).get("logins", [{}])[0].get("token", "")
    assert token2 == token, (
      f"Token changed after idempotent re-run: before={token!r} after={token2!r}"
    )
    print("PASS: API token unchanged after idempotent re-run (ISSUE-REQ-14 satisfied)")

    print("=== service-account-cli-config: all tests passed ===")
  '';
}
