{
  config,
  pkgs,
  lib,
  ...
}: {
  # Minimal Keystone server configuration for VM testing
  # This configuration enables nixos-anywhere deployment to VMs

  # NixOS state version - do not change after initial deployment
  system.stateVersion = "25.05";

  # System identity
  networking.hostName = "keystone-test-vm";
  # Required for ZFS - unique 8-character hex string
  # Generate with: head -c 4 /dev/urandom | od -A none -t x4 | tr -d ' '
  networking.hostId = "deadbeef";

  # Enable Keystone OS configuration
  keystone.os = {
    enable = true;

    # Storage configuration with ZFS and encryption
    storage = {
      type = "zfs";
      # Disk device for VM testing
      # Note: VMs use /dev/vda - disk-by-id serial doesn't work reliably with quickemu
      devices = ["/dev/vda"];

      # Partition sizes
      swap.size = "8G";
    };

    # Enable Secure Boot with lanzaboote
    secureBoot.enable = true;

    # Enable TPM-based automatic unlock
    tpm = {
      enable = true;
      pcrs = [1 7];
    };

    # SSH-based remote disk unlocking for VMs
    # The host key is automatically generated by bin/test-deployment
    # and copied to /etc/ssh/initrd_ssh_host_ed25519_key via --extra-files
    remoteUnlock = {
      enable = true;
      authorizedKeys = [
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOyrDBVcGK+pUZOTUA7MLoD5vYK/kaPF6TNNyoDmwNl2 ncrmro@ncrmro-laptop-fw7k"
      ];
      networkModule = "virtio_net"; # For QEMU/KVM VMs
    };

    # Test user for ZFS user module verification
    users.testuser = {
      uid = 1001;
      fullName = "Test User for ZFS Verification";
      email = "testuser@keystone-test-vm";
      initialPassword = "testpass"; # Test only - insecure
      terminal.enable = true;
      zfs = {
        quota = "10G";
        compression = "lz4";
      };
    };
  };

  # Server services (SSH, mDNS, firewall, etc.)
  keystone.server.enable = true;

  # Serial console support for VM testing
  # Enables console output via serial port (useful for password prompts in initrd)
  boot.kernelParams = [
    "console=ttyS0,115200n8" # Serial console
    "console=tty0" # Keep VGA console as fallback
  ];

  # Enable serial console in systemd (for initrd password prompts)
  boot.initrd.systemd.emergencyAccess = true; # Allow emergency access via serial

  # Ensure virtio modules are available in initrd (required for QEMU/KVM VMs)
  boot.initrd.availableKernelModules = ["virtio_blk" "virtio_pci" "virtio_net"];

  # SSH access configuration
  # IMPORTANT: Replace with your actual SSH public key(s)
  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOyrDBVcGK+pUZOTUA7MLoD5vYK/kaPF6TNNyoDmwNl2 ncrmro@ncrmro-laptop-fw7k"
  ];

  # Allow testuser to receive nix store paths over SSH (for home-manager testing)
  nix.settings.trusted-users = ["root" "testuser"];

  # Additional packages for Secure Boot provisioning
  environment.systemPackages = with pkgs; [
    sbctl # Secure Boot key management tool (required for post-install provisioning)
  ];
}
