---
apiVersion: v1
kind: Namespace
metadata:
  name: @@namespace@@
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
  namespace: @@namespace@@
data:
  config.yaml: |
    server_url: @@serverUrl@@
    listen_addr: 0.0.0.0:8080
    metrics_listen_addr: 0.0.0.0:9090
    grpc_listen_addr: 0.0.0.0:50443
    grpc_allow_insecure: false
    private_key_path: /var/lib/headscale/private.key
    noise:
      private_key_path: /var/lib/headscale/noise_private.key
    prefixes:
      v4: 100.64.0.0/10
      v6: fd7a:115c:a1e0::/48
    derp:
      server:
        enabled: true
        private_key_path: /var/lib/headscale/derp_private.key
        region_id: 999
        region_code: "headscale"
        region_name: "Headscale Embedded"
        stun_listen_addr: "0.0.0.0:3478"
      urls:
        - https://controlplane.tailscale.com/derpmap/default
      auto_update_enabled: true
      update_frequency: 24h
    disable_check_updates: false
    ephemeral_node_inactivity_timeout: 30m
    database:
      type: sqlite
      sqlite:
        path: /var/lib/headscale/db.sqlite
    dns:
      magic_dns: true
      base_domain: @@baseDomain@@
      nameservers:
        global:
          - 1.1.1.1
          - 8.8.8.8
    log:
      format: text
      level: info@@pvcResource@@
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headscale
  namespace: @@namespace@@
  labels:
    app: headscale
spec:
  replicas: @@replicas@@
  selector:
    matchLabels:
      app: headscale
  template:
    metadata:
      labels:
        app: headscale
    spec:
      containers:
        - name: headscale
          image: @@image@@
          command:
            - headscale
            - serve
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 50443
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
            - name: stun
              containerPort: 3478
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /etc/headscale
              readOnly: true
            - name: data
              mountPath: /var/lib/headscale@@keysVolumeMounts@@
          resources:
            requests:
              cpu: @@requestsCpu@@
              memory: @@requestsMemory@@
            limits:
              cpu: @@limitsCpu@@
              memory: @@limitsMemory@@
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config
          configMap:
            name: headscale-config
@@dataVolume@@@@keysVolume@@
---
apiVersion: v1
kind: Service
metadata:
  name: headscale
  namespace: @@namespace@@
spec:
  type: NodePort
  selector:
    app: headscale
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30080
    - name: grpc
      port: 50443
      targetPort: grpc
    - name: stun
      port: 3478
      targetPort: stun
      protocol: UDP
