#!/usr/bin/env bash
# compose.sh — Assembles a final prompt from a centralized archetype definition.
#
# Output order: shared/ defaults → roles/ → conventions/

set -euo pipefail

# Resolve the directory of this script, which acts as AGENTS_REPO
AGENTS_REPO="$(cd "$(dirname "$0")" && pwd)"
ARCHETYPES_FILE="$AGENTS_REPO/archetypes.yaml"

usage() {
  cat <<'USAGE'
Usage: compose.sh <archetype> <role>
       compose.sh <archetype> --agent-md

Positional:
  archetype   The agent archetype (e.g., engineer, product) defined in archetypes.yaml
  role        Role name to compose (e.g., code-reviewer), or --agent-md to generate AGENTS.md

Optional:
  -h, --help  Show this help

Environment variables (expanded via envsubst when available):
  $AGENT_NAME           Name of the agent
  $ROLE                 Current role name

Examples:
  conventions/compose.sh engineer code-reviewer
  conventions/compose.sh product --agent-md
USAGE
  exit 0
}

# --- Parse arguments ---

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
fi

if [[ $# -lt 2 ]]; then
  echo "Error: two positional arguments required: <archetype> <role>" >&2
  echo "Run with --help for usage." >&2
  exit 1
fi

ARCHETYPE="$1"
ROLE="$2"

if [[ ! -f "$ARCHETYPES_FILE" ]]; then
  echo "Error: archetypes file not found at $ARCHETYPES_FILE" >&2
  exit 1
fi

if ! command -v yq &>/dev/null; then
  echo "Error: yq is required but not found in PATH." >&2
  echo "Install: https://github.com/mikefarah/yq" >&2
  exit 1
fi

# Verify archetype exists
if [[ $(yq ".archetypes.$ARCHETYPE" "$ARCHETYPES_FILE") == "null" ]]; then
  echo "Error: archetype '$ARCHETYPE' not found in $ARCHETYPES_FILE" >&2
  exit 1
fi

# --- Helper: emit a file with a separator ---

emit_file() {
  local filepath="$1"
  if [[ -f "$filepath" ]]; then
    echo ""
    echo "---"
    echo ""
    cat "$filepath"
  else
    echo "Warning: file not found: $filepath" >&2
  fi
}

# --- Resolve and emit fragments ---

collect() {
  # 1. Shared defaults (hardcoded for now as they apply to all agents)
  emit_file "$AGENTS_REPO/shared/rfc2119-preamble.md"
  emit_file "$AGENTS_REPO/shared/output-format-rules.md"

  local role_path=".archetypes.$ARCHETYPE.roles.$ROLE"

  if [[ $(yq "$role_path" "$ARCHETYPES_FILE") == "null" ]]; then
    echo "Error: role '$ROLE' not found in archetype '$ARCHETYPE'" >&2
    exit 1
  fi

  # 2. Emit the primary role file
  emit_file "$AGENTS_REPO/roles/$ROLE.md"

  # 3. Conventions from role config
  local conv_count
  conv_count=$(yq "$role_path.conventions | length" "$ARCHETYPES_FILE" 2>/dev/null || echo "0")
  for ((i = 0; i < conv_count; i++)); do
    local conv
    conv=$(yq "$role_path.conventions[$i]" "$ARCHETYPES_FILE")
    emit_file "$AGENTS_REPO/$conv.md"
  done
}

# --- Main ---

compose_agent_md() {
  echo "<!--"
  echo "  Generated by compose.sh"
  echo "  Archetype: $ARCHETYPE"
  echo "  Command:   conventions/compose.sh $ARCHETYPE --agent-md > AGENTS.md"
  echo "-->"
  echo ""
  echo "@SOUL.md"
  echo "@TEAM.md"
  echo "@SERVICES.md"
  echo ""
  echo "# Agent Space"
  echo ""
  echo "This repository is an agent space designed to encapsulate an agent's"
  echo "long-term memory, process tools, and operational context."
  echo ""
  echo "## Context"
  echo ""
  echo "Current and completed tasks are in \`TASKS.yaml\`."
  echo ""
  echo "## Identity and Accounts"
  echo ""
  echo "You MUST always use your own accounts and credentials as defined in"
  echo "\`SOUL.md\`. Never use the human's accounts, credentials, or OAuth flows."
  echo ""
  echo "# Conventions"
  echo ""
  echo "Read about the convention system in [conventions/AGENTS.md](conventions/AGENTS.md)."

  local inlined_count
  inlined_count=$(yq ".archetypes.$ARCHETYPE.inlined_conventions | length" "$ARCHETYPES_FILE" 2>/dev/null || echo "0")
  for ((i = 0; i < inlined_count; i++)); do
    local conv
    conv=$(yq ".archetypes.$ARCHETYPE.inlined_conventions[$i]" "$ARCHETYPES_FILE")
    local conv_path="$AGENTS_REPO/$conv.md"
    if [[ -f "$conv_path" ]]; then
      echo ""
      cat "$conv_path"
    else
      echo "Warning: inlined convention not found: $conv_path" >&2
    fi
  done

  echo ""
  echo "## References"
  echo ""

  local ref_count
  ref_count=$(yq ".archetypes.$ARCHETYPE.referenced_conventions | length" "$ARCHETYPES_FILE" 2>/dev/null || echo "0")
  for ((i = 0; i < ref_count; i++)); do
    local conv
    conv=$(yq ".archetypes.$ARCHETYPE.referenced_conventions[$i]" "$ARCHETYPES_FILE")
    if [[ "$conv" != "null" ]]; then
      echo "- [$conv]($conv.md)"
    fi
  done
}

export ROLE

if [[ "$ROLE" == "--agent-md" ]]; then
  compose_agent_md
else
  if command -v envsubst &>/dev/null; then
    collect | envsubst
  else
    collect
  fi
fi