# Hardware configuration for Apple Silicon
# Generated by install-apple-silicon
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [];

  # Root filesystem (ext4 - ZFS not supported on Asahi kernel)
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  # Boot partition (Asahi ESP)
  fileSystems."/boot" = {
    device = "/dev/disk/by-partuuid/456551a3-4160-44c0-8763-b5dd56969569";
    fsType = "vfat";
  };

  # No swap configured (add manually if needed)
  # swapDevices = [ { device = "/dev/disk/by-label/swap"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
