# Podman container runtime for keystone hosts.
#
# Enables rootless Podman with fuse-overlayfs (required for ZFS), disables
# Docker, and conditionally installs sandbox tooling (agentctl, podman-agent)
# when the terminal sandbox module is active. Also exposes a small rootless
# Quadlet workload API for long-running app containers.
#
# See conventions/process.sandbox-agent.md
# Implements REQ-013 (Container Sub-Agent Management)
{
  config,
  lib,
  pkgs,
  options,
  utils,
  ...
}:
with lib;
let
  osCfg = config.keystone.os;
  cfg = osCfg.containers;
  # Check if terminal sandbox is enabled (home-manager module)
  hasSandbox = options ? keystone && config.keystone.terminal.sandbox.enable or false;

  enabledWorkloads = filterAttrs (_: workload: workload.enable) cfg.workloads;

  renderEnvironmentValue = value: toString value;

  renderQuadlet =
    name: workload:
    let
      registryLoginScript = pkgs.writeShellScript "keystone-container-${name}-registry-login" ''
        set -euo pipefail

        if [ -r ${escapeShellArg workload.registryLogin.passwordFile} ]; then
          exec ${pkgs.podman}/bin/podman login \
            --username ${escapeShellArg workload.registryLogin.username} \
            --password-stdin \
            ${escapeShellArg workload.registryLogin.registry} \
            < ${escapeShellArg workload.registryLogin.passwordFile}
        fi
      '';

      unitLines = [
        "[Unit]"
        "Description=${workload.description}"
      ]
      ++ optional workload.wantsNetworkOnline "After=network-online.target"
      ++ optional workload.wantsNetworkOnline "Wants=network-online.target"
      ++ workload.unit.extraLines;

      containerLines = [
        "[Container]"
        "ContainerName=${workload.containerName}"
        "Image=${workload.image}"
      ]
      ++ optional (workload.workingDir != null) "WorkingDir=${workload.workingDir}"
      ++ optional workload.autoUpdate "AutoUpdate=registry"
      ++ mapAttrsToList (
        key: value: "Environment=${key}=${renderEnvironmentValue value}"
      ) workload.environment
      ++ map (environmentFile: "EnvironmentFile=${environmentFile}") workload.environmentFiles
      ++ map (port: "PublishPort=${port}") workload.ports
      ++ map (volume: "Volume=${volume}") workload.volumes
      ++ map (secret: "Secret=${secret}") workload.secrets
      ++ map (network: "Network=${network}") workload.networks
      ++ map (arg: "PodmanArgs=${arg}") workload.podmanArgs
      ++ workload.container.extraLines;

      serviceLines = [
        "[Service]"
        "Restart=${workload.restart}"
        "RestartSec=${workload.restartSec}"
        "TimeoutStartSec=${workload.timeoutStartSec}"
      ]
      ++ optional workload.registryLogin.enable "ExecStartPre=${registryLoginScript}"
      ++ workload.service.extraLines;

      installLines = [ "[Install]" ] ++ map (target: "WantedBy=${target}") workload.wantedBy;
    in
    pkgs.writeText "keystone-container-${name}.container" (
      concatStringsSep "\n" (
        [
          "# Generated by keystone.os.containers.workloads.${name}."
          "# Do not edit by hand."
          ""
        ]
        ++ unitLines
        ++ [ "" ]
        ++ containerLines
        ++ [ "" ]
        ++ serviceLines
        ++ [ "" ]
        ++ installLines
        ++ [ "" ]
      )
    );

  workloadQuadletRules = concatLists (
    mapAttrsToList (
      name: workload:
      let
        quadletFile = renderQuadlet name workload;
        quadletDir = "${workload.home}/.config/containers/systemd";
        quadletPath = "${quadletDir}/${workload.serviceName}.container";
      in
      optional workload.createHome "d ${workload.home} 0700 ${workload.user} ${workload.group} - -"
      ++ [
        "d ${workload.home}/.config 0700 ${workload.user} ${workload.group} - -"
        "d ${workload.home}/.config/containers 0700 ${workload.user} ${workload.group} - -"
        "d ${quadletDir} 0755 ${workload.user} ${workload.group} - -"
        "L+ ${quadletPath} - - - - ${quadletFile}"
      ]
    ) enabledWorkloads
  );

  workloadUserManagerServices = mapAttrs' (name: workload: {
    name = "keystone-container-workload-${utils.escapeSystemdPath name}";
    value = {
      description = "Start lingering user manager for Keystone container workload ${name}";
      wantedBy = [ "multi-user.target" ];
      after = [ "systemd-user-sessions.service" ];
      path = [
        pkgs.coreutils
        pkgs.systemd
      ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
      };
      script = ''
        uid="$(id -u ${escapeShellArg workload.user})"
        systemctl start "user@$uid.service"
      '';
    };
  }) enabledWorkloads;
in
{
  options.keystone.os.containers = {
    enable = mkOption {
      type = types.bool;
      default = osCfg.enable;
      description = "Enable Podman container runtime by default for all keystone hosts";
    };

    workloads = mkOption {
      default = { };
      description = ''
        Long-running rootless Podman workloads rendered as per-user Quadlet
        `.container` files. This API is for stable service contracts: NixOS owns
        users, ports, mounts, secrets, and reverse-proxy integration while the
        registry can move a mutable image tag such as `latest` for fast app-only
        deploys.
      '';
      type = types.attrsOf (
        types.submodule (
          { name, config, ... }:
          {
            config = {
              group = mkDefault config.user;
              home = mkDefault "/var/lib/keystone-containers/${config.user}";
              containerName = mkDefault config.serviceName;
            };

            options = {
              enable = mkEnableOption "rootless Podman Quadlet workload";

              user = mkOption {
                type = types.str;
                example = "svc-vega";
                description = "Local user whose rootless Podman/systemd instance owns this workload.";
              };

              group = mkOption {
                type = types.str;
                defaultText = literalExpression "config.user";
                description = "Primary group for a module-created workload user.";
              };

              createHome = mkOption {
                type = types.bool;
                default = true;
                description = ''
                  Create the workload home directory with systemd-tmpfiles. The
                  user account itself must be declared by the consumer or another
                  Keystone module.
                '';
              };

              allowForgejoRunnerUser = mkOption {
                type = types.bool;
                default = false;
                description = ''
                  Allow this app workload to run as the Forgejo Actions runner
                  user. Defaults to false so app services do not share rootless
                  Podman state, registry auth, or volumes with CI jobs.
                '';
              };

              home = mkOption {
                type = types.str;
                defaultText = literalExpression ''"/var/lib/keystone-containers/''${config.user}"'';
                description = "Home directory that contains the user's rootless Quadlet search path.";
              };

              image = mkOption {
                type = types.str;
                example = "git.example.com/owner/app:latest";
                description = "OCI image reference consumed by Quadlet's Image= setting.";
              };

              description = mkOption {
                type = types.str;
                default = "Keystone container workload ${name}";
                description = "Systemd unit description for the generated workload.";
              };

              serviceName = mkOption {
                type = types.str;
                default = name;
                description = "Base service name; `${serviceName}.container` generates `${serviceName}.service`.";
              };

              containerName = mkOption {
                type = types.str;
                defaultText = literalExpression "config.serviceName";
                description = "Podman container name.";
              };

              workingDir = mkOption {
                type = types.nullOr types.str;
                default = null;
                example = "/app";
                description = "Optional container working directory.";
              };

              wantsNetworkOnline = mkOption {
                type = types.bool;
                default = true;
                description = "Add network-online ordering to the generated unit.";
              };

              autoUpdate = mkOption {
                type = types.bool;
                default = true;
                description = "Emit `AutoUpdate=registry` so `podman auto-update` can pull changed tags.";
              };

              ports = mkOption {
                type = types.listOf types.str;
                default = [ ];
                example = [ "127.0.0.1:17878:17878" ];
                description = "Quadlet PublishPort= entries.";
              };

              volumes = mkOption {
                type = types.listOf types.str;
                default = [ ];
                example = [ "/var/lib/vega:/var/lib/vega" ];
                description = "Quadlet Volume= entries.";
              };

              environment = mkOption {
                type = types.attrsOf (
                  types.oneOf [
                    types.str
                    types.int
                    types.bool
                  ]
                );
                default = { };
                description = "Environment variables passed to the container.";
              };

              environmentFiles = mkOption {
                type = types.listOf types.str;
                default = [ ];
                description = "Quadlet EnvironmentFile= entries. Use runtime paths such as /run/agenix/... for secrets.";
              };

              secrets = mkOption {
                type = types.listOf types.str;
                default = [ ];
                example = [ "vega-token,type=mount,target=token,mode=0400" ];
                description = "Quadlet Secret= entries for Podman secrets already present for the workload user.";
              };

              networks = mkOption {
                type = types.listOf types.str;
                default = [ ];
                description = "Quadlet Network= entries.";
              };

              podmanArgs = mkOption {
                type = types.listOf types.str;
                default = [ ];
                description = "Additional Quadlet PodmanArgs= entries.";
              };

              restart = mkOption {
                type = types.str;
                default = "always";
                description = "Systemd Restart= policy for the generated service.";
              };

              restartSec = mkOption {
                type = types.str;
                default = "5";
                description = "Systemd RestartSec= value for the generated service.";
              };

              timeoutStartSec = mkOption {
                type = types.str;
                default = "300";
                description = "Systemd TimeoutStartSec= value for slow image pulls.";
              };

              wantedBy = mkOption {
                type = types.listOf types.str;
                default = [ "default.target" ];
                description = "WantedBy= targets for the generated user service.";
              };

              registryLogin = {
                enable = mkEnableOption "registry login before starting this workload";

                registry = mkOption {
                  type = types.str;
                  default = "git.ncrmro.com";
                  description = "Registry hostname passed to `podman login`.";
                };

                username = mkOption {
                  type = types.str;
                  default = "";
                  description = "Registry username. The password/token stays in passwordFile.";
                };

                passwordFile = mkOption {
                  type = types.str;
                  default = "/run/agenix/${name}-container-registry-token";
                  defaultText = literalExpression ''"/run/agenix/''${name}-container-registry-token"'';
                  description = "Runtime file containing the registry password/token. Its contents are not copied into the Nix store.";
                };
              };

              unit.extraLines = mkOption {
                type = types.listOf types.str;
                default = [ ];
                description = "Extra raw lines appended to the Quadlet [Unit] section.";
              };

              container.extraLines = mkOption {
                type = types.listOf types.str;
                default = [ ];
                description = "Extra raw lines appended to the Quadlet [Container] section.";
              };

              service.extraLines = mkOption {
                type = types.listOf types.str;
                default = [ ];
                description = "Extra raw lines appended to the generated service's [Service] section.";
              };
            };
          }
        )
      );
    };
  };

  config = mkIf (osCfg.enable && cfg.enable) (mkMerge [
    {
      virtualisation.containers.enable = true;
      # CRITICAL: fuse-overlayfs required for rootless podman on ZFS — kernel
      # overlayfs cannot mount on ZFS for unprivileged users (permission denied).
      virtualisation.containers.storage.settings.storage.options.mount_program =
        "${pkgs.fuse-overlayfs}/bin/fuse-overlayfs";
      virtualisation.docker.enable = lib.mkForce false;
      virtualisation.podman = {
        enable = true;
        # Provides the `docker` CLI shim so existing docker-based tooling
        # (scripts, compose files, IDE integrations) works transparently
        # against podman. Safe because `virtualisation.docker.enable` is
        # forced off above, so the shim never collides with real Docker.
        dockerCompat = true;
        dockerSocket.enable = true;
        defaultNetwork.settings.dns_enabled = true;
      };

      # Grant the admin user membership in the `podman` group. The group
      # itself is already created by the upstream podman module
      # (nixos/modules/virtualisation/podman/default.nix declares
      # `users.groups.podman = { };` unconditionally when virtualisation.podman
      # is enabled), so no `users.groups.podman = {};` is needed here.
      #
      # Non-admin wheel users do NOT get this automatically — hardware/service
      # access follows `admin = true`, not sudo. See
      # conventions/process.user-groups.md.
      keystone.os._autoUserGroups.adminOnly = [ "podman" ];

      environment.systemPackages =
        with pkgs;
        [
          dive
          docker-compose
        ]
        ++ lib.optionals hasSandbox [
          pkgs.keystone.agentctl
          pkgs.keystone.podman-agent
        ];
    }

    (mkIf (enabledWorkloads != { }) {
      assertions = mapAttrsToList (name: workload: {
        assertion = workload.allowForgejoRunnerUser || workload.user != "gitea-runner";
        message = ''
          keystone.os.containers.workloads.${name} uses user "gitea-runner".
          App workloads must not share the Forgejo Actions runner's rootless
          Podman state unless allowForgejoRunnerUser is explicitly enabled.
        '';
      }) enabledWorkloads;

      systemd.tmpfiles.rules =
        workloadQuadletRules
        ++ map (workload: "f /var/lib/systemd/linger/${workload.user} 0644 root root -") (
          attrValues enabledWorkloads
        );
      systemd.services = workloadUserManagerServices;
    })
  ]);
}
