#!/usr/bin/env bash
# quickemu configuration for headed server VM

guest_os="linux"
iso="keystone-installer.iso"
disk_img="server/disk.qcow2"
disk_size="20G"
ram="4G"
cpu_cores="2"
display="gtk"
viewer="spicy"
ssh="22220"
spice="5930"
public_dir=""
usb_passthrough=""